### ISSUE TITLE
Lack of files

### ISSUE THREAD

**Issue by PierreKoung** [driehle/node-brother-label-printer#1]
Can you please upload all files ? because i see **require('ipp')** but i don't see the ipp library

**Comment by driehle** [comment]
@PierreKoung There is a `package.json` in the repository, which lists all required dependencies. You will need to install them using `npm install`.

**Comment by PierreKoung** [comment]
Yes. I did it. But the library doesn’t work on Angular. it has many deprecated dependencies

**Comment by driehle** [comment]
`ipp` (see https://www.npmjs.com/package/ipp) should not be related to Angular in any way. In general, `ipp` does the communication with the printer, for which it requires network access. If you are developing a browser-based Angular application, that will likely not work, since Browsers do not offer a low-level TCP client for Javascript applications. Hence, you can only use `ipp` and this library in a NodeJS environment, e.g. an Electron application.

**Comment by PierreKoung** [comment]
Got it. thanks for your reply.
