### ISSUE TITLE
how print a pdf instead of a png

### ISSUE THREAD

**Issue by AlexTaverna** [driehle/node-brother-label-printer#2]
i'm making an electron app that assembles the label in a html page, and then it gets saved as pdf, because of this, it gets impossible to print

**Comment by driehle** [comment]
First, let me quote the [README](https://github.com/driehle/node-brother-label-printer/blob/master/README.md) from this package:

> ### :warning: Library abandoned
> **Please note:** This library is considered a proof-of-concept and is neither actively maintained nor further developed.

Many brother label printers (maybe all?) do not support printing PDF files directly. They support a very simple protocol consisting of a matrix that has all the black and white pixels to be printed. See `convertImageToDotlabel()` in https://github.com/driehle/node-brother-label-printer/blob/master/lib/brother.js#L152 for details on the implementation of that protocol. 

To print a PDF you would have to render the PDF to a pixel image. Since PDFs are quite complex you should probably use an existing library for converting a PDF to an image, then you can send that image via IPP to the label printer.

An alternative solution could be to use the package `node-native-printer` (see https://github.com/MatteoMeil/node-native-printer). That package relies on the Brother printer driver to be installed on the machine that you sent the print command from. The benefit is that you can print anything that you can print with desktop applications (including PDF files), you are not restricted to Brother label printers and you can use any printer installed on your machine. The downside is that you cannot send print commands from mobile devices, as Brother print drivers are only available for Windows, Mac and Linux.
